package cz.silesnet.service.impl;

import cz.silesnet.dao.UserDAO;
import cz.silesnet.service.HistoryManager;
import cz.silesnet.service.UserManager;
import cz.silesnet.utils.SecurityUtils;
import org.acegisecurity.event.authentication.InteractiveAuthenticationSuccessEvent;
import org.acegisecurity.providers.UsernamePasswordAuthenticationToken;
import org.acegisecurity.ui.WebAuthenticationDetails;
import org.acegisecurity.ui.session.HttpSessionDestroyedEvent;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.List;

/**
 * User manager implementation, mainly to log users in.
 *
 * @author Richard Sikora
 */
public class UserManagerImpl implements UserManager {

  // ~ Instance fields
  // --------------------------------------------------------

  protected final Log log = LogFactory.getLog(getClass());

  private UserDAO dao;

  private HistoryManager hmgr;

  // ~ Methods
  // ----------------------------------------------------------------

  // wired by Spring

  public void setHistoryManager(HistoryManager historyManager) {
    hmgr = historyManager;
  }

  // method used by spring 2 wire HibernateDAO implementation here

  public void setUserDAO(UserDAO dao) {
    this.dao = dao;
  }

  public List getUsers() {
    return dao.getUsers();
  }

  public void dispatchSessionDestroyedEvent(
      HttpSessionDestroyedEvent sessionEvent) {
    log.info("Dispatching session destroyed event.");
    hmgr.updateLogout(sessionEvent.getSession());

    // TODO kick off user from user cache in acegi
  }

  public void dispatchSuccessfulLoginEvent(
      InteractiveAuthenticationSuccessEvent authEvent) {
    // we have Acegis succesfull login event here, let's store it
    log.info("Dispatching successful user login event.");
    log.debug("Generated by: " + authEvent.getGeneratedBy());

    // retrieve web authentication details
    WebAuthenticationDetails wad = (WebAuthenticationDetails) ((UsernamePasswordAuthenticationToken) authEvent
        .getSource()).getDetails();
    // FIXME retreve user corectly here from event
    hmgr.insertLogin(SecurityUtils.getUser(), wad.getRemoteAddress(), wad
        .getSessionId());
  }
}